### ISSUE TITLE
typing Print exits the program

### ISSUE THREAD

**Issue by codebroker40** [mucsci-students/2020sp-420-ascii_shrug#16]
**Describe the bug**
typing print in the repl exits the program

**To Reproduce**
1. build project
2. run `java -cp target/uml-0.1.0.jar Repl`
3. type `print`

**Expected behavior**
Not exit the program, run the print function

**Desktop (please complete the following information):**
 - OS: Debian on Windows Subsystem for Linux

**Comment by jackfazio** [comment]
Switch case did not have return. Fixed.
