### ISSUE TITLE
Running tests leaves test.json in root directory

### ISSUE THREAD

**Issue by codebroker40** [mucsci-students/2020sp-420-ascii_shrug#37]
**Describe the bug**
Running tests leaves json files in directory

**To Reproduce**
Run mvn package or mvn test
See test.json in project root directory

**Expected behavior**
Test shouldn't leave files there

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ma1526** [comment]
fixed

**Comment by codebroker40** [comment]
fixed in #42
