### ISSUE TITLE
GUI on osX

### ISSUE THREAD

**Issue by jackfazio** [mucsci-students/2020sp-420-ascii_shrug#56]
**Describe the bug**

**To Reproduce**
Run the gui on osX. The swing pane will not render.

**Expected behavior**
The swing pane should render.

**Comment by willkill07** [comment]
Additional Information:

This is a known bug with JDK + JavaFX 11 and newer. The patch has been made but will only be applicable for versions >= 14. I discussed alternatives with `ascii_shrug`

**Comment by jackfazio** [comment]
Fixed with JFXToSwing branch. Took approximately 2 hours with help from Professor Killian
