### ISSUE TITLE
Relationships being removed on class edit

### ISSUE THREAD

**Issue by jackfazio** [mucsci-students/2020sp-420-ascii_shrug#93]
**Describe the bug**
Relationships are removed upon adding attributes.

**To Reproduce**
Add attributes to a class in the GUI, and it's relationships will be removed

**Expected behavior**
Relationships should stay and the attributes should be changed

**Desktop (please complete the following information):**
Linux and OSx

**Additional context**
Likely occurring in diagram.execute()

**Comment by codebroker40** [comment]
Fixed in https://github.com/mucsci-students/2020sp-420-ascii_shrug/pull/94
